CREATE TABLE [dbo].[Players]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	Lastname VARCHAR(50) NOT NULL,
	Firstname VARCHAR(50) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Nickname VARCHAR(50) NOT NULL,
	Password VARCHAR(MAX) NOT NULL
)
